### ISSUE TITLE
SipMask-benchmark

### ISSUE THREAD

**Issue by trungpham2606** [JialeCao001/SipMask#3]
@JialeCao001 
Thank for sharing such a great work!
Iam testing your work based on maskrcnn-benchmark.
But there seems a missing of make_data_loader in fcos_core folder ?
![image](https://user-images.githubusercontent.com/35657426/89246283-0133bc80-d635-11ea-9d84-c2c918070d81.png)

**Comment by JialeCao001** [comment]
@trungpham2606 hi, it seems that I ignore the folder of fcos_core/data. I have updated it.

**Comment by trungpham2606** [comment]
@JialeCao001 
Still doesnt have make_data_loader.py file ?
Please recheck your code 
![image](https://user-images.githubusercontent.com/35657426/89268116-47ebdb80-d662-11ea-9d2c-04b977d33548.png)

**Comment by JialeCao001** [comment]
@trungpham2606 It is a function in build.py, not a single file. https://github.com/JialeCao001/SipMask/blob/20959f4d07a83579dc731753c85ab062413a9483/SipMask-benchmark/fcos_core/data/build.py#L107

**Comment by GK-6686** [comment]
@JialeCao001 
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 152, in main
    cfg.merge_from_file(args.config_file)
  File "/home/gk/.conda/envs/FCOS/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/gk/.conda/envs/FCOS/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/gk/.conda/envs/FCOS/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/gk/.conda/envs/FCOS/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.SIPMASK_ON'

Thanks for your sharing!
I am train your work based on maskrcnn-benchmark. But there was an error like the one above, I hope you can give me some advice, thank you!
