### ISSUE TITLE
Non-existent config key: MODEL.SIPMASK_ON

### ISSUE THREAD

**Issue by omerbrandis** [JialeCao001/SipMask#34]
hello Sipmask community,

This is my first attempt at using SipMask, so I guess this is some sort of installation error.

**i've followed install.md :**   
installed FCOS ,
cloned SipMask, 
cd SipMask-benchmark
python tools/test_net.py --config-file configs/sipmask/sipmask_R_50_FPN_1x.yaml MODEL.WEIGHT  training_dir/SipMask_R50_1x.pth TEST.IMS_PER_BATCH 4

**sadly, received the following error :**
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 49, in main
    cfg.merge_from_file(args.config_file)
  File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
**KeyError: 'Non-existent config key: MODEL.SIPMASK_ON'**

any ideas?
Omer

**Comment by JialeCao001** [comment]
@omerbrandis  You donot need to install original FCOS. Just clone SipMask, cd SipMask, install it. The install (compile) step is same as original FCOS.

**Comment by omerbrandis** [comment]
I executed python setup.py build develop --no-deps from SipMask_benchmark , it solved the problem.
thank you very much.
Omer
