### ISSUE TITLE
python setup.py develop ERROR

### ISSUE THREAD

**Issue by JackeyZhang1001** [JialeCao001/SipMask#54]
When I execute this command:`python setup.py develop`
and when the following information is printed on the terminal:
`Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)`
It will return the error:
```
 File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

```
I don't know if there's something wrong with my settings. I would appreciate it if someone has the same problem and can help me solve this problem.

**Comment by JackeyZhang1001** [comment]
the full error information is :
```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /root/Desktop/SipMask/SipMask-VIS/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.7m -c -c /root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp -o /root/Desktop/SipMask/SipMask-VIS/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /root/Desktop/SipMask/SipMask-VIS/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o 
c++ -MMD -MF /root/Desktop/SipMask/SipMask-VIS/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.7m -c -c /root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp -o /root/Desktop/SipMask/SipMask-VIS/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ���-Wstrict-prototypes��� is valid for C/ObjC but not for C++
In file included from /opt/conda/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:2:
/opt/conda/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp: In function ���at::Tensor nms(const at::Tensor&, float)���:
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ���at::DeprecatedTypeProperties& at::Tensor::type() const��� is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ���CHECK_CUDA���
   CHECK_CUDA(dets);
   ^~~~~~~~~~
In file included from /opt/conda/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /opt/conda/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:2:
/opt/conda/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ���AT_CHECK��� was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ���CHECK_CUDA���
   CHECK_CUDA(dets);
   ^~~~~~~~~~
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ���DCHECK���
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/root/Desktop/SipMask/SipMask-VIS/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ���CHECK_CUDA���
   CHECK_CUDA(dets);
   ^~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 215, in <module>
    zip_safe=False)
  File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by NikolaZubicWonder** [comment]
@JackeyZhang1001 did you manage to solve the problem ?
