### ISSUE TITLE
About training process in the Youtube-VIS dataset.

### ISSUE THREAD

**Issue by lartpang** [JialeCao001/SipMask#6]
<details>
<summary> My Config </summary>

```python
# model settings
model = dict(
    type="SipMask",
    # pretrained="open-mmlab://resnet50_caffe",
    backbone=dict(
        type="ResNet",
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type="BN", requires_grad=False),
        style="caffe",
    ),
    neck=dict(
        type="FPN",
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs=True,
        extra_convs_on_inputs=False,  # use P5
        num_outs=5,
        relu_before_extra_convs=True,
    ),
    bbox_head=dict(
        type="SipMaskHead",
        num_classes=41,
        in_channels=256,
        stacked_convs=3,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        loss_cls=dict(
            type="FocalLoss", use_sigmoid=True, gamma=2.0, alpha=0.25, loss_weight=1.0
        ),
        loss_bbox=dict(type="IoULoss", loss_weight=1.0),
        loss_centerness=dict(
            type="CrossEntropyLoss", use_sigmoid=True, loss_weight=1.0
        ),
        center_sampling=True,
        center_sample_radius=1.5,
    ),
)
# training and testing settings
train_cfg = dict(
    assigner=dict(
        type="MaxIoUAssigner",
        pos_iou_thr=0.5,
        neg_iou_thr=0.4,
        min_pos_iou=0,
        ignore_iof_thr=-1,
    ),
    allowed_border=-1,
    pos_weight=-1,
    debug=False,
)
test_cfg = dict(
    nms_pre=200,
    min_bbox_size=0,
    score_thr=0.03,
    nms=dict(type="nms", iou_thr=0.5),
    max_per_img=10,
)
# dataset settings
dataset_type = "YTVOSDataset"
data_root = "/home/lart/Datasets/VideoSeg/YoutubeVIS2019/"
img_norm_cfg = dict(
    mean=[102.9801, 115.9465, 122.7717], std=[1.0, 1.0, 1.0], to_rgb=False
)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + "Train/train.json",
        img_prefix=data_root + "Train/JPEGImages",
        img_scale=[(649, 360), (960, 480)],
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=True,
        with_crowd=True,
        with_label=True,
        with_track=True,
    ),
    val=dict(
        type=dataset_type,
        ann_file=data_root + "Valid/valid.json",
        img_prefix=data_root + "Valid/JPEGImages",
        img_scale=(640, 360),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_crowd=True,
        with_label=True,
    ),
    test=dict(
        type=dataset_type,
        ann_file=data_root + "Valid/valid.json",
        img_prefix=data_root + "Valid/JPEGImages",
        img_scale=(640, 360),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True,
    ),
)

# optimizer
optimizer = dict(
    type="SGD",
    lr=0.005,
    momentum=0.9,
    weight_decay=0.0001,
    paramwise_options=dict(bias_lr_mult=2.0, bias_decay_mult=0.0),
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy="step",
    warmup="linear",
    warmup_iters=1000,
    warmup_ratio=1.0 / 80,
    step=[8, 11],
)
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=10,
    hooks=[
        dict(type="TextLoggerHook"),
        # dict(type='TensorboardLoggerHook')
    ],
)
# yapf:enable
# runtime settings
total_epochs = 12
device_ids = range(8)
dist_params = dict(backend="nccl")
log_level = "INFO"
work_dir = "./work_dirs/sipmask_r50_fpn_ms_1x"
load_from = None
resume_from = None
workflow = [("train", 1)]
```

</details>

When I train the code on the trainset of the Youtube-VIS, it outputs such an error message:

<details>
<summary> ERROR MESSAGE </summary>

```shell
➜ ./tools/dist_train.sh ./configs/sipmask/sipmask_r50_caffe_fpn_gn_ms_train.py 2
2020-08-08 13:08:35,462 - INFO - Distributed training: True
loading annotations into memory...
loading annotations into memory...
Done (t=7.55s)
creating index...
index created!
Done (t=7.63s)
creating index...
index created!
2020-08-08 13:09:34,491 - INFO - Start running, host: lart@god, work_dir: /home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/work_dirs/sipmask_r50_fpn_ms_1x
2020-08-08 13:09:34,491 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 110, in <module>
    main()
  File "./tools/train.py", line 106, in main
    logger=logger)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/models/detectors/single_stage.py", line 66, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore, gt_masks_list=gt_masks, ref_bboxes_list = ref_bboxes, gt_pids_list=gt_pids)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/models/anchor_heads/sipmask_head.py", line 497, in loss
    loss_match += cross_entropy(prod_ext, cur_ids)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/models/losses/cross_entropy_loss.py", line 11, in cross_entropy
    loss = F.cross_entropy(pred, label, reduction='none')
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 2: non-empty vector or matrix expected at /tmp/pip-req-build-xea91aoh/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31
Traceback (most recent call last):
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/lart/miniconda3/envs/sipmask/bin/python', '-u', './tools/train.py', '--local_rank=0', './configs/sipmask/sipmask_r50_caffe_fpn_gn_ms_train.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

</details>

But, if I set the item from `imgs_per_gpu=2` to `imgs_per_gpu=4`, it works well:

<details>
<summary> MESSAGE </summary>

```shell
➜ ./tools/dist_train.sh ./configs/sipmask/sipmask_r50_caffe_fpn_gn_ms_train.py 2
2020-08-08 13:10:36,074 - INFO - Distributed training: True
/home/lart/miniconda3/envs/sipmask/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
loading annotations into memory...
loading annotations into memory...
Done (t=7.70s)
creating index...
index created!
Done (t=7.76s)
creating index...
index created!
2020-08-08 13:11:35,432 - INFO - Start running, host: lart@god, work_dir: /home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/work_dirs/sipmask_r50_fpn_ms_1x
2020-08-08 13:11:35,432 - INFO - workflow: [('train', 1)], max: 12 epochs
2020-08-08 13:11:54,687 - INFO - Epoch [1][10/7669]     lr: 0.00011, eta: 2 days, 0:49:07, time: 1.910, data_time: 1.400, memory: 5320, loss_cls: 1.0477, loss_bbox: 2.2564, loss_centerness: 0.6610, loss_mask: 0.6855, loss_match: 1.6922, match_acc: 78.6566, loss: 6.3429
2020-08-08 13:11:59,198 - INFO - Epoch [1][20/7669]     lr: 0.00016, eta: 1 day, 6:08:53, time: 0.449, data_time: 0.025, memory: 5342, loss_cls: 1.0134, loss_bbox: 0.8200, loss_centerness: 0.6511, loss_mask: 0.6491, loss_match: 1.2980, match_acc: 80.7617, loss: 4.4316
^CTraceback (most recent call last):
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/distributed/launch.py", line 228, in main
    process.wait()
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
VISProj/SipMaskDockerProj/SipMask-VIS via 🐍 v3.6.10 :: Anaconda, Inc. via C sipmask took 2m8s 
➜ Traceback (most recent call last):
  File "./tools/train.py", line 110, in <module>
    main()
  File "./tools/train.py", line 106, in main
    logger=logger)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/core/utils/dist_utils.py", line 58, in after_train_iter
Traceback (most recent call last):
  File "./tools/train.py", line 110, in <module>
    main()
  File "./tools/train.py", line 106, in main
    logger=logger)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lart/Coding/VISProj/SipMaskDockerProj/SipMask-VIS/tools/../mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    runner.optimizer.step()
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/optim/sgd.py", line 100, in step
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lart/miniconda3/envs/sipmask/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    buf.mul_(momentum).add_(1 - dampening, d_p)
KeyboardInterrupt
    allow_unreachable=True)  # allow_unreachable flag
KeyboardInterrupt
```

</details>

**Comment by JialeCao001** [comment]
@lartpang Please change L459 as follows. I am not sure about the performance using a small batch-size.
https://github.com/JialeCao001/SipMask/blob/28a3329b59b731dafc7996fcb172ddc2d8685bf2/SipMask-VIS/mmdet/models/anchor_heads/sipmask_head.py#L459

**Comment by lartpang** [comment]
Thanks! @JialeCao001 It works well.
